name: "Lint (pull request)"

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Validate PR Title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          if ! echo "$PR_TITLE" | grep -E '^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert|tweak)(\(.+\))?!?: [A-Z].+$'; then
            echo "PR title '$PR_TITLE' does not follow conventional commit format"
            exit 1
          fi
